# This file controls the AWS CodeBuild

version: 0.2

phases:
  install:
    runtime-versions:
      docker: 19
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --no-include-email --region us-east-2)
      - REPOSITORY_URI=873130424562.dkr.ecr.us-east-2.amazonaws.com/jdbanksecurity
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
  build:
    commands:
      - mvn clean install
      - echo Entered the build phase...
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t 873130424562.dkr.ecr.us-east-2.amazonaws.com/jdbanksecurity:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed successfully
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push 873130424562.dkr.ecr.us-east-2.amazonaws.com/jdbanksecurity:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
artifacts:
  files:
    - target/security.jar
  discard-paths: yes